// ---------------------------------------------------------------------------
// Scattergories category prompts. Each round draws a handful at random.
// Phrased to work with any starting letter and to be fun for remote teams.
// ---------------------------------------------------------------------------

export const SCATTER_CATEGORIES: string[] = [
  'A type of food',
  'An animal',
  'A country',
  'A city',
  'A movie',
  'A TV show',
  'A boy or girl name',
  'Something in an office',
  'Something you bring on a video call',
  'A job or profession',
  'A reason you are late to a meeting',
  'A hobby',
  'A type of drink',
  'A piece of clothing',
  'A sport',
  'A musical instrument',
  'A board game or video game',
  'A color',
  'A car brand',
  'Something in the kitchen',
  'A thing in nature',
  'A school subject',
  'A famous person',
  'A superhero or villain',
  'An app or website',
  'Something you would pack for vacation',
  'A type of weather',
  'A fictional character',
  'A breakfast food',
  'A thing with wheels',
  'A musical artist or band',
  'Something cold',
  'Something hot',
  'A body part',
  'A holiday',
  'A type of shoe',
  'Something in a backpack',
  'A pizza topping',
  'A excuse for skipping the gym',
  'A type of bird',
  'Something round',
  'A thing you find at the beach',
  'A word to describe your boss',
  'Something you do on Monday',
  'A flower or plant',
  'A type of dance',
  'A candy or dessert',
  'Something electronic',
  'A planet or space thing',
  'A river, lake, or ocean',
  'A tool',
  'Something in a garden',
  'A type of cheese',
  'A villain in a movie',
  'A thing that flies',
  'Something you keep on your desk',
  'A book or comic',
  'A type of bread',
  'A mythical creature',
  'Something you would never eat',
];
